//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("780, 460")]
        public global::System.Drawing.Size FormMainSize {
            get {
                return ((global::System.Drawing.Size)(this["FormMainSize"]));
            }
            set {
                this["FormMainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point FormMainLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormMainLocation"]));
            }
            set {
                this["FormMainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormMainWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormMainWindowState"]));
            }
            set {
                this["FormMainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GlobalDirectoryRoot {
            get {
                return ((string)(this["GlobalDirectoryRoot"]));
            }
            set {
                this["GlobalDirectoryRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\markets\\")]
        public string GlobalDirectoryMarkets {
            get {
                return ((string)(this["GlobalDirectoryMarkets"]));
            }
            set {
                this["GlobalDirectoryMarkets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\logs\\")]
        public string GlobalDirectoryLogs {
            get {
                return ((string)(this["GlobalDirectoryLogs"]));
            }
            set {
                this["GlobalDirectoryLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\work\\")]
        public string GlobalDirectoryWork {
            get {
                return ((string)(this["GlobalDirectoryWork"]));
            }
            set {
                this["GlobalDirectoryWork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\data\\")]
        public string GlobalDirectoryData {
            get {
                return ((string)(this["GlobalDirectoryData"]));
            }
            set {
                this["GlobalDirectoryData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\plugins\\")]
        public string GlobalDirectoryPlugins {
            get {
                return ((string)(this["GlobalDirectoryPlugins"]));
            }
            set {
                this["GlobalDirectoryPlugins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\reports\\")]
        public string GlobalDirectoryReports {
            get {
                return ((string)(this["GlobalDirectoryReports"]));
            }
            set {
                this["GlobalDirectoryReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IXNDX")]
        public string GlobalMarket {
            get {
                return ((string)(this["GlobalMarket"]));
            }
            set {
                this["GlobalMarket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999")]
        public int FormStrategyEvolverPopulationConstraint {
            get {
                return ((int)(this["FormStrategyEvolverPopulationConstraint"]));
            }
            set {
                this["FormStrategyEvolverPopulationConstraint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int randomMinIndicators {
            get {
                return ((int)(this["randomMinIndicators"]));
            }
            set {
                this["randomMinIndicators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int randomMaxIndicators {
            get {
                return ((int)(this["randomMaxIndicators"]));
            }
            set {
                this["randomMaxIndicators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int randomMinPeriod {
            get {
                return ((int)(this["randomMinPeriod"]));
            }
            set {
                this["randomMinPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252")]
        public int randomMaxPeriod {
            get {
                return ((int)(this["randomMaxPeriod"]));
            }
            set {
                this["randomMaxPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormStrategyEvolverRandomChanceChecked {
            get {
                return ((bool)(this["FormStrategyEvolverRandomChanceChecked"]));
            }
            set {
                this["FormStrategyEvolverRandomChanceChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormStrategyEvolverNaturalSelectionChecked {
            get {
                return ((bool)(this["FormStrategyEvolverNaturalSelectionChecked"]));
            }
            set {
                this["FormStrategyEvolverNaturalSelectionChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormStrategyEvolverGeneticEvolutionChecked {
            get {
                return ((bool)(this["FormStrategyEvolverGeneticEvolutionChecked"]));
            }
            set {
                this["FormStrategyEvolverGeneticEvolutionChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormStrategyEvolverNaturalSelectionOOSChecked {
            get {
                return ((bool)(this["FormStrategyEvolverNaturalSelectionOOSChecked"]));
            }
            set {
                this["FormStrategyEvolverNaturalSelectionOOSChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1095")]
        public int GlobalPeriod {
            get {
                return ((int)(this["GlobalPeriod"]));
            }
            set {
                this["GlobalPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.99")]
        public double BrokerCommision {
            get {
                return ((double)(this["BrokerCommision"]));
            }
            set {
                this["BrokerCommision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\schedules\\")]
        public string GlobalDirectorySchedules {
            get {
                return ((string)(this["GlobalDirectorySchedules"]));
            }
            set {
                this["GlobalDirectorySchedules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public double AccountInitialBalance {
            get {
                return ((double)(this["AccountInitialBalance"]));
            }
            set {
                this["AccountInitialBalance"] = value;
            }
        }
    }
}
